name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Update APT database
      run: sudo apt-get -yq update || true
    - name: Install OS packages for building
      run: sudo apt-get -yq --no-install-suggests --no-install-recommends --force-yes install libsdl1.2-dev build-essential gcc make
    - name: List of all installed packages
      run: dpkg -l | cat || true
    - name: Modifying the build system
      run: pwd ; hostname ; sudo hostname actions.github.com || true ; sudo adduser --home `pwd` --shell /bin/bash --no-create-home --disabled-password --disabled-login --gecos "LGB builder" lgb && sudo chown -R lgb:lgb .
    - name: Show system status
      run: cat /etc/debian_version ; lsb_release -a ; gcc --version | head -n 1 ; make --version | head -n 1 ; bash --version | head -n 1 ; uname -a ; id -a ; echo "CWD is `pwd`" ; echo "PATH is $PATH" ; echo "Hostname is `hostname`" ; uptime ; df -h . ; ls -la .
    - name: Show native SDL1.2 status
      run: ls -l `which sdl-config` || true ; sdl-config --version --prefix --exec-prefix --cflags --libs --static-libs || true
    - name: Compiling for native (Linux)
      run: sudo -u lgb make -j 2
    - name: Show result
      run: ls -l bin/ ; ldd bin/fake86 || true
    - name: Showing output of an emulator
      run: bin/fake86 -h || true
